domain_path: /home/liji/data/fpga/prj/pynq-ssd/vitis/pynq-ssd-platform-freertos/export/pynq-ssd-platform-freertos/sw/freertos_ps7_cortexa9_0
app_src_dir: /opt/xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/freertos_hello_world
template: freertos_hello_world
lang: c
