domain_path: /data/work/fpga/prj/germ/vitis/GeRM-192-384/export/GeRM-192-384/sw/freertos_ps7_cortexa9_0
app_src_dir: /opt/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
